Ut 59 ron
amavumkal/utopia-angular pull request #14
Opened 2021-01-26 02:55 UTC by ronhenson

2021-01-26 20:13 UTC, PatrickSmoothstack reviewed
Looks pretty straightforward.

2021-01-27 16:13 UTC, dereklance requested changes

2021-01-27 16:13 UTC, dereklance commented on src/app/components/toolbar/toolbar.component.scss
> +}
new line

2021-01-27 16:13 UTC, dereklance commented on src/app/components/login/login.component.ts
> +              this.token = this.route.snapshot.paramMap.get('token');
we don't need this token for anything

2021-01-27 16:13 UTC, dereklance commented on src/app/components/login/login-routing.module.ts
> +  path: '../booking/flight',
why does the path start with `../`

2021-01-27 16:53 UTC, dereklance requested changes

2021-01-27 16:53 UTC, dereklance commented on src/app/components/login/login-routing.module.ts
> +import { NgModule } from '@angular/core';
why do we need this file? we already have the /booking/flight route defined in the app module.

2021-01-27 16:53 UTC, dereklance commented on src/app/components/login/login.component.ts
> +      this.router.navigate(['../booking/flight']);
shouldn't this be `booking/flight` instead of `../booking/flight`?

2021-01-27 17:16 UTC, dereklance approved these changes

2021-01-27 17:19 UTC, dereklance approved these changes

2021-01-27 17:19 UTC, merged