Arun
amavumkal/utopia-angular pull request #2
Opened 2021-01-16 22:29 UTC by amavumkal

Created signup form.

2021-01-16 23:21 UTC, dereklance requested changes

2021-01-16 23:21 UTC, dereklance commented on src/app/utility/validators/passwordMismatch.ts
> +  if (password.value && password.value && password.value === confirmPassword.value) {
checking `password.value` twice

2021-01-16 23:59 UTC, dereklance approved these changes

2021-01-16 23:59 UTC, merged

2021-01-21 21:37 UTC, ronhenson commented on src/app/components/signup/signup.component.ts
> +import {AfterContentInit, Component, OnInit, ViewChild} from '@angular/core';
remove Viewchild - not used

2021-01-21 21:37 UTC, ronhenson commented on src/app/components/signup/signup.component.ts
> +    private authService: AuthService,
refactor change name authservice to userService

2021-01-21 21:37 UTC, ronhenson commented on src/app/services/api/auth.service.ts
> +  postUser(payload: any): any {
change "any" type by using interface

2021-01-21 21:37 UTC, ronhenson commented on src/app/services/api/auth.service.ts
> +  postUser(payload: any): any {
insert try catch

2021-01-21 21:37 UTC, ronhenson commented on src/app/services/api/auth.service.ts
> +    const url = this.URL + '/auth/sign-up';
techdebt: naming the api auth to user??

2021-01-21 21:37 UTC, ronhenson commented on src/app/utility/validators/passwordMismatch.ts
> +  if (password.value && password.value === confirmPassword.value) {
parenthesis to make easier to read password.value confirmPassword