Flight search form
amavumkal/utopia-angular pull request #3
Opened 2021-01-17 23:43 UTC by dereklance

2021-01-18 02:07 UTC, amavumkal commented on src/app/components/flight-search-page/shared/types.ts
> +  ONE_WAY = 'One Way'
Add a newline

2021-01-18 02:08 UTC, amavumkal requested changes

2021-01-18 02:08 UTC, amavumkal commented on src/app/shared/types.ts
> +  leg2: FlightModel
Add a new line

2021-01-18 02:08 UTC, amavumkal commented on src/app/components/flight-search-page/shared/types.ts
> +export enum TripType {
Add a newline

2021-01-18 02:08 UTC, amavumkal commented on src/app/components/flight-search-page/flight-search/flight-search.component.ts
> +  }
Add a newline

2021-01-18 04:53 UTC, dereklance reviewed
Created new branch to fix all linting errors, including adding new lines to end of files

2021-01-18 07:52 UTC, amavumkal approved these changes

2021-01-18 15:18 UTC, merged

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/airport-search-modal/airport-search-modal.component.ts
> +  location = Location.ORIGIN
Rename to something meaningful

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/airport-table/airport-table.component.ts
> +    this.eventService.emitAirportSelected(airport, this.location)
Change name of event service

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/airport-table/airport-table.component.ts
> +  }
Add comment to explain what this service is for

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/flight-search/flight-search.component.ts
> +  originAirport: Airport = { iataIdent: 'LAX', city: 'Los Angeles, CA', name: 'Los Angeles International' }
Remove default values

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/flight-search/flight-search.component.ts
> +    private eventService: EventService,
refactor service name.

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/services/airport-search.service.ts
> +  apiUrl = 'http://localhost:8085/airport?query='
add url to environment file.

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/services/airport-search.service.ts
> +    return this.http.get<Airport[]>(this.apiUrl + query)
handle errors here instead of where the observable is consumed

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/services/event.service.ts
> +export class EventService {
Rename service

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/flight-search-page/flight-search/flight-search.component.ts
> +import { FlightsService } from './../../../services/api/flights.service';
Refactor code - evaluate need for event service.

2021-01-21 20:58 UTC, amavumkal commented on src/app/components/toolbar/toolbar.component.html
> +    <span class="example-spacer"></span>
change name of css class

2021-01-21 20:58 UTC, amavumkal commented on src/app/services/api/flights.service.ts
> +        this.directFlights.next(flights)
Add try catch